### ISSUE TITLE
Grid "Add package to the grid" and other controls missing

### ISSUE THREAD

**Issue by santagada** [djangopackages/djangopackages#300]
The grid controls are missing on some of the grids and I don't think they are locked

Missing controls:
https://www.djangopackages.com/grids/g/asset-managers/
https://www.djangopackages.com/grids/g/cookiecutter/

With controls:
https://www.djangopackages.com/grids/g/forums/
https://www.djangopackages.com/grids/g/configuration/

it seems to be what was affecting #293 but now configuration grid has controls and some other grids don't anymore.

**Comment by tomchristie** [comment]
Weirdly this appears to be sporadic. The issue was resolved for the REST framework grid, which I assumed was due to @pydanny tweaking some configuration in response to this issue or similar, but the controls have since disappeared again. (Accessing from a different location, but still logged in. Also tried logging out and in again.) Very odd.

![screen shot 2015-01-07 at 21 22 11](https://cloud.githubusercontent.com/assets/647359/5653612/b1ef0574-96b3-11e4-94e2-bc656b6afd57.png)

**Comment by santagada** [comment]
I'm starting to think this a cache issue. The server either has cached a login version or a logged out... so the controls apear and vanish as the cache timesout

**Comment by tomchristie** [comment]
Sure, either a server-side or application caching issue sounds feasible.

**Comment by benebun** [comment]
Hey,

just to wake up this thread: This issue is still occurring and quite important I think. Otherwise djangopackages.com will slowly lose it's usefulness if it can't be updated easily (obviously). I keep coming across packages that are not up-to-date on the grids and it took me a while to figure out why (i.e. until I found this ticket).

To me it seems to be a caching issue as well:
* After logging in via github I didn't see any edit links on any grid, also not on the ones mentioned here where they did display.
* Returning to some grid views after about 1-2 hours and the edit links are now being displayed.
* Logging out and in again the edit links are not displayed again.
* It is not an authorisation issue because I can access the links directly when logged in, even though they are not displayed.

Hope that helps!

**Comment by jayfk** [comment]
Thanks, that helps a lot @benebun.  

I'm still unable to reproduce this in a reliable way. There's a lot of caching magic going on under the hood.
